extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - unused-imports
  - simple-import-sort
  - import
rules:
  no-shadow: off
  "@typescript-eslint/no-shadow": warn
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define": warn
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .tsx
  complexity:
    - error
    - 25
  no-await-in-loop: warn
  no-eval: error
  no-implied-eval: error
  prefer-promise-reject-errors: warn
  no-unused-vars: off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console:
    - warn
    - allow:
        - error
        - warn
        - debug
  no-debugger: warn
  no-var: error
  prefer-const: error
  eqeqeq:
    - error
    - smart
  curly:
    - warn
    - multi-or-nest
  arrow-parens:
    - error
    - always
  "@typescript-eslint/no-var-requires": off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-non-null-asserted-optional-chain": off
  "@typescript-eslint/no-explicit-any": warn
  no-multi-spaces: error
  "@typescript-eslint/no-unused-vars": error
  "@typescript-eslint/no-empty-function": error
  "@typescript-eslint/no-empty-interface": warn
  unused-imports/no-unused-imports-ts: error
  simple-import-sort/imports: off
  simple-import-sort/exports: error
  import/no-default-export: error
  camelcase: off
  react/react-in-jsx-scope: off
  nonblock-statement-body-position:
    - error
    - any
  "import/no-internal-modules": off
  "no-restricted-imports":
    - error
    - patterns:
        - "../*"
        - "src/*"
  "import/order":
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      pathGroups:
        - pattern: "@**/**"
          group: internal
          position: before
      pathGroupsExcludedImportTypes: []
      alphabetize:
        order: asc
        caseInsensitive: true
env:
  browser: true
settings:
  react:
    pragma: React
    version: "detect"
